backend:
  name: github
  branch: master
  repo: gilbertlucas46/gimilove

media_folder: static/img
public_folder: /img

collections: # A list of collections the CMS should be able to edit
  - name: 'header'
    label: 'Header Module'
    folder: "src/_data/header"
    create: true
    delete: false # Prevent users from deleting documents in this collection
    fields:
      - { label: 'Module Name', name: 'title', widget: 'string', required: true }
      - label: "Header"
        name: "header_module"
        widget: "object"
        fields:
          - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
          - {
              label: 'Wedding Date',
              name: 'date',
              widget: 'datetime',
              dateFormat: 'YYYY-MM-DD',
              timeFormat: 'HH:mm',
              format: 'YYYY-MM-DD HH:mm',
            }
          - label: 'Cover Image'
            name: 'image'
            widget: 'image'
            required: false
            tagname: ''
          - { editorComponents: ['youtube'], required: false, label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }

  - name: "metadata"
    label: "Metadata & Navigation"
    description: "Pages Metadatas"
    folder: "src/metadata"
    create: false
    fields:
      - { label: 'Update Metadata & Navigation', name: 'title', widget: 'string',  default: "Metadata & Navigation" }
      - label: "MetaData's"
        name: "metadata"
        widget: "object"
        fields:
          - { label: "Meta Title", name: "metatitle", widget: "string" }
          - { label: "Title Template", name: "titleTemplate", widget: "hidden", default: "%s · Gilbert Lucas" }
          - { label: "About Description", name: metadesc, widget: 'markdown' }
          - { label: "Author", name: "author", widget: "hidden", default: "Gilbert lucas" }
          - { label: "url", name: "url", widget: "hidden", default: "https://gilbert.codes" }
          - { label: "siteUrl", name: "siteUrl", widget: "hidden", default: "https://gilbert.codes" }
          - {
            label: Image,
            name: image,
            required: false,
            hint: "Image for the page",
            widget: image,
          }
          - { label: "Owner", name: "owner", widget: "hidden", default: "Gilbertlucas" }
          - { label: "Page name", name: "pagetitle", widget: "string" }
          - { label: "twitterUsername", name: "url", widget: "hidden", default: "@gilbertlucas14" }
          - { label: "facebookAppID", name: "url", widget: "hidden", default: " " }

      - label: "Menu Links"
        name: "menuLinks"
        widget: "list"
        fields:
          [
            { label: "Page Name", name: "name", widget: "string" },
            { label: "Link to", name: link, widget: 'string' }
          ]

      - label: "Social Channels"
        name: "socialChannels"
        widget: "list"
        fields:
          [
            { label: "Social Channel Name", name: "name", widget: "string" },
            { label: "Link to", name: link, widget: 'string' }
          ]

  - name: 'about'
    label: 'About Us'
    folder: 'src/_data/about'
    create: true
    description: 'Information about us'
    fields:
      - { label: 'Module Name', name: 'title', widget: 'string', required: true }
      - label: 'Info'
        name: about
        widget: 'object'
        fields:
          - { label: 'Name', name: 'title', widget: 'string' }
          - {
              label: 'Photo',
              name: image,
              widget: image,
              required: false,
            }
          - { label: 'Description', name: 'text', widget: 'text', hint: 'Plain text, not markdown' }


  - name: 'location'
    label: 'Where and When'
    folder: 'src/_data/location'
    create: true
    description: 'Information location and contact'
    fields:
      - { label: 'Module Name', name: 'title', widget: 'string', required: true }
      - label: "Where and When"
        name: "loc"
        widget: "object"
        fields:
          - {label: "Description", name: "name", widget: "markdown"}
      - label: "Contact"
        name: "contact"
        widget: "object"
        fields:
          - {label: "Description", name: "name", widget: "markdown"}
  - name: 'rsvp'
    label: 'RSVP'
    delete: false # Prevent users from deleting documents in this collection
    folder: 'src/_data/rsvp'
    create: true
    fields:
      - { label: 'Module Name', name: 'title', widget: 'string', required: true }
      - label: "rsvp"
        name: "RSVP"
        widget: "object"
        fields:
          - {label: "Message", name: "name", widget: "markdown"}

  - name: 'footer'
    label: 'Footer'
    delete: false # Prevent users from deleting documents in this collection
    folder: 'src/_data/footer'
    create: true
    fields:
      - { label: 'Module Name', name: 'title', widget: 'string', required: true }
      - label: "Footer"
        name: "footer"
        widget: "object"
        fields:
          - {label: "Message", name: "name", widget: "markdown"}

  - name: 'gallery'
    label: 'Gallery'
    delete: false # Prevent users from deleting documents in this collection
    folder: 'src/_data/gallery'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', default: 'Wedding Image', required: false }
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        media_library:
          config:
            multiple: true
      - { label: 'Description', name: 'desc', widget: 'text', required: false }